### ISSUE TITLE
Could not read manifest.json file

### ISSUE THREAD

**Issue by c0rky** [LaserlikeInc/firefox-addon#82]
I installed/verified web-ext in node.js command prompt.
in the readme, the next step is:
    cd laserlike-extension/firefox
    web-ext run
but there is no such  path in installed dir.
I tried making the path, extract "firefox-addon-master.zip" in it and >"web-ext run", the result:
    "Could not read manifest.json file ..."
Could somebody explain what I'm doing wrong please?

**Comment by pdehaan** [comment]
@c0rky You may need to run <kbd>$ npm run build</kbd>. I think the **addon/manifest.json** file is generated as part of https://github.com/LaserlikeInc/firefox-addon/blob/8588af1533226f00b14012146a53d2ede8a2e09c/package.json#L37

**Comment by c0rky** [comment]
![firefox-addon](https://user-images.githubusercontent.com/12856022/44378671-b4678180-a502-11e8-9eef-7435e312e4d5.PNG)


Content of **2018-08-21T03_24_21_469Z-debug.log**
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Advance@0.9.41~prebuild: Advance@0.9.41
6 info lifecycle Advance@0.9.41~build: Advance@0.9.41
7 verbose lifecycle Advance@0.9.41~build: unsafe-perm in lifecycle true
8 verbose lifecycle Advance@0.9.41~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;c:\Users\Haze\AppData\Roaming\npm\node_modules\web-ext\tests\laserlike-extension\firefox\node_modules\.bin;c:\Users\Haze\AppData\Roaming\npm\node_modules\.bin;C:\Users\Haze\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\nodejs\;C:\Ruby25-x64\bin;C:\Users\Haze\AppData\Local\Microsoft\WindowsApps;C:\Users\Haze\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\Haze\AppData\Roaming\npm
9 verbose lifecycle Advance@0.9.41~build: CWD: c:\Users\Haze\AppData\Roaming\npm\node_modules\web-ext\tests\laserlike-extension\firefox
10 silly lifecycle Advance@0.9.41~build: Args: [ '/d /s /c', 'npm-run-all build:*' ]
11 silly lifecycle Advance@0.9.41~build: Returned: code: 1  signal: null
12 info lifecycle Advance@0.9.41~build: Failed to exec build script
13 verbose stack Error: Advance@0.9.41 build: `npm-run-all build:*`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid Advance@0.9.41
15 verbose cwd c:\Users\Haze\AppData\Roaming\npm\node_modules\web-ext\tests\laserlike-extension\firefox
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.11.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error Advance@0.9.41 build: `npm-run-all build:*`
22 error Exit status 1
23 error Failed at the Advance@0.9.41 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by pdehaan** [comment]
Looks like **npm-run-all** wasn't installed. Did you run `npm install` after cloning the repo?

**Comment by pdehaan** [comment]
@c0rky Here were the steps that I did locally:

```sh
# using macOS "High Sierra" (v 10.13.6)
$ git clone https://github.com/LaserlikeInc/firefox-addon.git
$ cd firefox-addon
$ npm install # using node v8.11.4 (npm v5.6.0)
$ npm start # which runs `npm run build` (builds manifest.json) and `npm run run` (launches Firefox).
```

**Comment by c0rky** [comment]
I'm using win 10

I'm trying to follow your method, installed Git Bash, so I could clone the repo.
In firefox-addon\ I installed npm, but doing so, returned the following warns:

> - npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4  (node_modules\fsevents):
> - npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

I'm not sure if they are relevant.

`$ npm start`
Returned a bunch of errors again, now saying

> The syntax of the command is incorrect.
> - npm ERR! code ELIFECYCLE
> - npm ERR! errno 1
> - npm ERR! Advance@0.9.41 build:ga: `mkdir -p addon/build && cp $(node -e 'console.log(require.resolve("testpilot-ga"))') addon/build/testpilot-ga.js`
> - npm ERR! Exit status 1

So it seems the problem is with a line of script in **package.json**?
`"#36: build:ga": "mkdir -p addon/build && cp $(node -e 'console.log(require.resolve(\"testpilot-ga\"))') addon/build/testpilot-ga.js",`

As far as I know, this command creates a folder structure and saves, whatever this code
`$(node -e 'console.log(require.resolve(\"testpilot-ga\"))')`
supposed to accomplish in that folder as **testpilot-ga.js**. 

Is there a typo I'm blind to? Or simply blind, period? :) 
I really apprericate your help, thanks for your replies!

**Comment by pdehaan** [comment]
Ah, OK... Yeah, I'm on macOS (which is more or less Linux), so I'd expect there will eventually be some differences for OS-specific shell commands (unless you're running something like cygwin or powershell or whatever is popular on Windows these days).

First, I'll _assume_ that the "npm WARN" are simply warnings and aren't stopping anything from working.

Now, for your package.json:L36 in question...

https://github.com/LaserlikeInc/firefox-addon/blob/3e680e0bfc0dcbc2233fc9f2a15fb8c786d6bbc0/package.json#L36

We can break that down into separate commands and I can try and explain it a bit better.

```sh
# Create an "./addon/build/" directory, if one doesn't exist.
$ mkdir -p addon/build

# Copy the "main" file from the "testpilot-ga" dependency into the newly created 
# "./addon/build/" directory, and name the file "testpilot-ga.js".
$ cp $(node -e 'console.log(require.resolve(\"testpilot-ga\"))') addon/build/testpilot-ga.js
```

You could try running those commands separately and see which specific one is failing. 

It looks like Windows has some level of [`mkdir`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mkdir) support, but there is a small possibility it's failing on the `-p` flag.

My guess is that it'd fail on the second part of that command, which is using some `$(node -e '')` shell magic to get the location of the **testpilot-ga** package's main file in the ./node_modules/ directory.

Plus, I think in Windows, it may be the [`copy`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/copy) command and not `cp`.

So, let's look at the [**testpilot-ga** module](https://github.com/mozilla/testpilot-ga/blob/250adf1420b1e74a5b36ab9d51e1cb1b6e2df85b/package.json#L5) and figure out what the "main" entrypoint is:

```js
{
  "name": "testpilot-ga",
  "version": "0.3.0",
  "description": "A library for event-driven data collection with Google Analytics for Firefox Test Pilot.",
  "main": "dist/index.js",
  // ...
}
```

So I think on Windows, you may need to try something like this (give or take some backslashes or forward slashes or however your specific shell handles folders):

```sh
$ copy ./node_modules/testpilot-ga/dist/index.js addon/build/testpilot-ga.js
```

That may be enough to get you unstuck from the current problem and onto the next one.
